[project]
name = "rafflechain"
description = "Provably fair on-chain raffles"
authors = ["solidworkssa"]
telemetry = false
cache_dir = ".cache"

[contracts.rafflechain]
path = "contracts/rafflechain.clar"

[repl.analysis]
passes = ["check_checker"]
